<?php

namespace AppBundle\Repository;
use Doctrine\DBAL\DBALException;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByText($text)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('u')
            ->from('AppBundle\Entity\Product', 'u')
            ->where('u.text = :text')
            ->setParameter('text', $text);

        $con = $this->_em->getConnection();
        $sql = "SELECT skaicius FROM product WHERE text='belekas'";
        try {
            $stmt = $con->prepare($sql);
            $stmt->execute();
        }catch(DBALException $er){
         echo 'Nepavyko prisijungimas';
         die();
        }


        return $qb->getQuery()->getResult();
    }

}
