security:

    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
#        in_memory:
#            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login

            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/confOrder, roles:ROLE_USER }

    encoders:
        AppBundle\Entity\User: bcrypt


